WEBSOCKET ws://localhost:8000/websocket
Content-Type: application/json

{
    "procedure": "createSalesItem",
    "argument": {
      "name": "Sales item 1",
      "priceInCents": 1000,
      "images": [
        {
          "rank": 1,
          "url": "http://www.something.com/url1"
        },
        {
          "rank": 2,
          "url": "http://www.something.com/url2"
        }
      ]
    }
}

###
WEBSOCKET ws://localhost:8000/websocket
Content-Type: application/json

{
    "procedure": "getSalesItems"
}

###
WEBSOCKET ws://localhost:8000/websocket
Content-Type: application/json

{
    "procedure": "getSalesItem",
    "argument": "4121807b-c822-4575-9012-ee2b30eb9368"
}

###
WEBSOCKET ws://localhost:8000/websocket
Content-Type: application/json

{
    "procedure": "updateSalesItem",
    "argument": {
      "id": "4121807b-c822-4575-9012-ee2b30eb9368",
      "name": "Sales item 22",
      "priceInCents": 1000,
      "images": [
        {
          "rank": 1000,
          "url": "http://www.something.com/url1"
        },
        {
          "rank": 2000,
          "url": "http://www.something.com/url2"
        }
      ]
    }
}

###
WEBSOCKET ws://localhost:8000/websocket
Content-Type: application/json

{
    "procedure": "deleteSalesItem",
    "argument": "4121807b-c822-4575-9012-ee2b30eb9368"
}