package com.example.orderservice.dtos;

import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;


// Input DTOs declare the structure and validations for
// input from clients
// Domain entity is created based on input DTO
// Below, we don't declare the 'id' field because it is
// generated by the server
// We also declare that 'userAccountId' must be a string with
// maximum size of 36 characters and that there can be
// maximum of 500 order items in a single order
@Data
@AllArgsConstructor
@NoArgsConstructor
public class InputOrder {
  @NotNull
  @NotBlank
  @Size(max=36)
  private String userAccountId;

  @Valid
  @NotNull
  @Size(max=500)
  private List<IOOrderItem> orderItems;
}

