spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: public
  datasource:
    url: jdbc:mysql://localhost:3306/public
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  graphql:
    graphiql:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-bean-definition-overriding: true


