GRAPHQL http://localhost:8080/graphql

query ordersByUserAccountId($userAccountId: ID!) {
    ordersByUserAccountId(userAccountId: $userAccountId) {
        id
        userAccountId
        orderItems {
            id
            salesItemId
            quantity
        }
    }
}

{
  "userAccountId": "3"
}

<> 2024-04-09T120156.200.json
<> 2024-04-09T120149.200.json
<> 2024-04-09T120144.200.json
<> 2024-04-09T120036.200.json

###
GRAPHQL http://localhost:8080/graphql

query orderById($id: ID!) {
  orderById(id: $id) {
      id
      userAccountId
      orderItems {
          id
          salesItemId
          quantity
      }
  }
}

{
   "id": "2f632e13-b1ef-4cdb-ad89-58779a9b8392"
}

<> 2024-04-09T120139.200.json
<> 2024-04-09T120039.200.json
<> 2024-04-09T115941.200.json
<> 2024-04-09T115843.200.json
<> 2024-04-09T115838.200.json
<> 2024-04-09T115822.200.json
<> 2024-04-09T115815.200.json
<> 2024-04-09T115633.200.json
<> 2024-04-09T115556.200.json

###
GRAPHQL http://localhost:8080/graphql

mutation createOrder {
    createOrder(inputOrder: {
        userAccountId: "2",
        orderItems: [
            {
                id: "c60a2f05-4f87-44d7-907f-b00c90c5181b",
                salesItemId: 2,
                quantity: 1
            },
            {
                id: "c60a2f05-4f87-44d7-907f-b00c90c5181c",
                salesItemId: 33,
                quantity: 33
            }
        ]
    }) {
        id
        userAccountId
        orderItems {
            id
            salesItemId,
            quantity
        }
    }
}

<> 2024-04-09T115506.200.json
